ibexa.compatibility_layer.oss:
    resource: 'deprecated_routing_oss.yaml'

datebasedpublisher_content_schedule_hide:
    alias: ibexa.scheduler.content.schedule.hide
    deprecated:
        package: ibexa/scheduler
        version: 4.0.0

datebasedpublisher_content_schedule_hide_cancel:
    alias: ibexa.scheduler.content.schedule.hide.cancel
    deprecated:
        package: ibexa/scheduler
        version: 4.0.0

datebasedpublisher_rest_scheduleVersion:
    alias: ibexa.scheduler.rest.schedule_version
    deprecated:
        package: ibexa/scheduler
        version: 4.0.0

datebasedpublisher_rest_rescheduleVersion:
    alias: ibexa.scheduler.rest.reschedule_version
    deprecated:
        package: ibexa/scheduler
        version: 4.0.0

datebasedpublisher_rest_unscheduleVersion:
    alias: ibexa.scheduler.rest.unschedule_version
    deprecated:
        package: ibexa/scheduler
        version: 4.0.0

datebasedpublisher_rest_getScheduledVersion:
    alias: ibexa.scheduler.rest.get_scheduled_version
    deprecated:
        package: ibexa/scheduler
        version: 4.0.0

datebasedpublisher_rest_getScheduledContentVersions:
    alias: ibexa.scheduler.rest.get_scheduled_content_versions
    deprecated:
        package: ibexa/scheduler
        version: 4.0.0

datebasedpublisher_rest_getScheduledVersions:
    alias: ibexa.scheduler.rest.get_scheduled_versions
    deprecated:
        package: ibexa/scheduler
        version: 4.0.0

datebasedpublisher_rest_getUserScheduledVersions:
    alias: ibexa.scheduler.rest.get_user_scheduled_versions
    deprecated:
        package: ibexa/scheduler
        version: 4.0.0

ezplatform.calendar.view:
    alias: ibexa.calendar.view
    deprecated:
        package: ibexa/calendar
        version: 4.0.0

ezplatform.calendar.rest.event.list.group_by_day:
    alias: ibexa.calendar.rest.event.list.group_by_day
    deprecated:
        package: ibexa/calendar
        version: 4.0.0

ezplatform.calendar.rest.event.list:
    alias: ibexa.calendar.rest.event.list
    deprecated:
        package: ibexa/calendar
        version: 4.0.0

ezplatform.calendar.rest.event.action:
    alias: ibexa.calendar.rest.event.action
    deprecated:
        package: ibexa/calendar
        version: 4.0.0

ezpublish_rest_binaryContent_getImageVariation:
    alias: ibexa.rest.binary_content.get_image_variation
    deprecated:
        package: ibexa/connector-dam
        version: 4.0.0

ibexa.platform.connector.dam.generic_search:
    alias: ibexa.connector.dam.generic_search
    deprecated:
        package: ibexa/connector-dam
        version: 4.0.0

ibexa.platform.connector.dam.asset_view:
    alias: ibexa.connector.dam.asset_view
    deprecated:
        package: ibexa/connector-dam
        version: 4.0.0

ibexa.platform.connector.dam.asset:
    alias: ibexa.connector.dam.asset
    deprecated:
        package: ibexa/connector-dam
        version: 4.0.0

ibexa.platform.connector.dam.asset_variation:
    alias: ibexa.connector.dam.asset_variation
    deprecated:
        package: ibexa/connector-dam
        version: 4.0.0

ez_recommendation.rest.content.get_by_id:
    alias: ibexa.personalization.rest.content.get_by_id
    deprecated:
        package: ibexa/personalization
        version: 4.0.0

ez_recommendation.rest.content.get_by_remote_id:
    alias: ibexa.personalization.rest.content.get_by_remote_id
    deprecated:
        package: ibexa/personalization
        version: 4.0.0

ez_recommendation.rest.export.download:
    alias: ibexa.personalization.rest.export.download
    deprecated:
        package: ibexa/personalization
        version: 4.0.0

ezplatform.version.side_by_side_comparison:
    alias: ibexa.version.side_by_side_comparison
    deprecated:
        package: ibexa/version-comparison
        version: 4.0.0

ezplatform.version.compare:
    alias: ibexa.version.compare
    deprecated:
        package: ibexa/version-comparison
        version: 4.0.0

ezplatform.workflow.transition.list:
    alias: ibexa.workflow.transition.list
    deprecated:
        package: ibexa/workflow
        version: 4.0.0

ezplatform.workflow.list:
    alias: ibexa.workflow.list
    deprecated:
        package: ibexa/workflow
        version: 4.0.0

ezplatform.workflow.view:
    alias: ibexa.workflow.view
    deprecated:
        package: ibexa/workflow
        version: 4.0.0

ezplatform.workflow.content_create.reviewer_suggest:
    alias: ibexa.workflow.content_create.reviewer_suggest
    deprecated:
        package: ibexa/workflow
        version: 4.0.0

ezplatform.workflow.content_edit.reviewer_suggest:
    alias: ibexa.workflow.content_edit.reviewer_suggest
    deprecated:
        package: ibexa/workflow
        version: 4.0.0
