services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    Ibexa\CompatibilityLayer\Event\EventDispatcher:
        decorates: 'event_dispatcher'
        arguments:
            $innerEventDispatcher: '@.inner'

    Ibexa\Bundle\CompatibilityLayer\Command\SymfonyConfigDebugCommand: ~

    Ibexa\Bundle\CompatibilityLayer\Command\SymfonyConfigDumpReferenceCommand: ~

    Ibexa\Bundle\CompatibilityLayer\Command\IbexaRebrandingCommand: ~

    Ibexa\Bundle\CompatibilityLayer\Twig\LegacyDesignThemeTemplateNameResolver: ~

    ibexa.compatibility.design_engine.legacy_twig_theme_loader:
        class: Ibexa\DesignEngine\Templating\Twig\TwigThemeLoader
        public: false
        arguments:
            $templateNameResolver: '@Ibexa\Bundle\CompatibilityLayer\Twig\LegacyDesignThemeTemplateNameResolver'
            $templatePathRegistry: '@Ibexa\DesignEngine\Templating\TemplatePathRegistry'
            $innerFilesystemLoader: '@twig.loader.filesystem'

    Ibexa\CompatibilityLayer\Routing\UrlAliasRouter:
        public: true
        arguments:
            - '@ibexa.api.service.location'
            - '@ibexa.api.service.url_alias'
            - '@ibexa.api.service.content'
            - '@Ibexa\Core\MVC\Symfony\Routing\Generator\UrlAliasGenerator'
            - "@?router.request_context"
            - "@?logger"
        calls:
            - [setConfigResolver, ['@ibexa.config.resolver']]
        tags:
            - {name: router, priority: 200}

    Ibexa\CompatibilityLayer\Event\Subscriber\RestMimeTypeSubscriber:
        tags:
            - { name: kernel.event_subscriber }
