services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    Ibexa\CompatibilityLayer\Routing\UrlWildcardRouter:
        public: true
        arguments:
            - '@ibexa.api.service.url_wildcard'
            - '@Ibexa\Core\MVC\Symfony\Routing\Generator\UrlAliasGenerator'
            - '@router.request_context'
        calls:
            - [ setLogger, [ '@?logger' ] ]
        tags:
            - { name: router, priority: 210 }
