<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
declare(strict_types=1);

return [
    'EzPlatformAdminUi' => 'IbexaAdminUi',
    'EzPlatformAdminUiAssets' => 'IbexaAdminUiAssets',
    'EzPlatformCalendar' => 'IbexaCalendar',
    'IbexaPlatformCommerceAdminUi' => 'IbexaCommerceAdminUi',
    'SisoContentPlugin' => 'IbexaCommerceBaseDesign',
    'IbexaPlatformCommerceCheckout' => 'IbexaCommerceCheckout',
    'SisoAdminErpPlugin' => 'IbexaCommerceErpAdmin',
    'IbexaPlatformCommerceFieldTypes' => 'IbexaCommerceFieldTypes',
    'SisoOrderHistory' => 'IbexaCommerceOrderHistory',
    'IbexaPlatformCommercePageBuilder' => 'IbexaCommercePageBuilder',
    'ShopPriceEnginePlugin' => 'IbexaCommercePriceEngine',
    'IbexaPlatformCommerceShopUi' => 'IbexaCommerceShopUi',
    'IbexaPlatformConnectorDam' => 'IbexaConnectorDam',
    'EzPlatformContentForms' => 'IbexaContentForms',
    'EzPlatformCron' => 'IbexaCron',
    'EzSystemsDateBasedPublisher' => 'IbexaScheduler',
    'EzPlatformDesignEngine' => 'IbexaDesignEngine',
    'PlatformElasticSearchEngine' => 'IbexaElasticsearch',
    'EzPlatformFormBuilder' => 'IbexaFormBuilder',
    'EzSystemsEzPlatformGraphQL' => 'IbexaGraphQL',
    'EzSystemsPlatformHttpCache' => 'IbexaHttpCache',
    'EzSystemsPlatformFastlyCache' => 'IbexaFastly',
    'IbexaPlatformIcons' => 'IbexaIcons',
    'EzPlatformMatrixFieldtype' => 'IbexaFieldTypeMatrix',
    'EzPlatformPageBuilder' => 'IbexaPageBuilder',
    'EzPlatformPageFieldType' => 'IbexaFieldTypePage',
    'PlatformPermissions' => 'IbexaPermissions',
    'IbexaPlatformPersonalization' => 'IbexaPersonalization',
    'EzSystemsEzPlatformQueryFieldType' => 'IbexaFieldTypeQuery',
    'EzRecommendationClient' => 'IbexaPersonalization',
    'EzPlatformRest' => 'IbexaRest',
    'EzPlatformRichText' => 'IbexaFieldTypeRichText',
    'IbexaPlatformSearch' => 'IbexaSearch',
    'IbexaPlatformSegmentation' => 'IbexaSegmentation',
    'EzPlatformSiteFactory' => 'IbexaSiteFactory',
    'EzSystemsEzPlatformSolrSearchEngine' => 'IbexaSolr',
    'EzPlatformStandardDesign' => 'IbexaStandardDesign',
    'EzSystemsEzSupportTools' => 'IbexaSystemInfo',
    'EzPlatformUser' => 'IbexaUser',
    'EzPlatformVersionComparison' => 'IbexaVersionComparison',
    'EzPlatformWorkflow' => 'IbexaWorkflow',
    'IbexaPlatformImageEditor' => 'IbexaImageEditor',
    'IbexaPlatformInstaller' => 'IbexaInstaller',
    'IbexaPlatformMigration' => 'IbexaMigration',
    'IbexaPlatformOAuth2Client' => 'IbexaOAuth2Client',
    'IbexaPlatformConnectorUnsplash' => 'IbexaConnectorUnsplash',
    'SisoRestApi' => 'IbexaCommerceRest',
    'EzPlatformCore' => 'IbexaCoreExtensions',
    'EzSystemsEzPlatformEncore' => 'IbexaEncore',
    'IbexaPlatformAssets' => 'IbexaIconSet',
    'EzPublishCore' => 'IbexaCore',
    'EzPublishDebug' => 'IbexaDebug',
    'EzPublishIO' => 'IbexaIO',
    'EzPublishLegacySearchEngineEzPublishLegacySearchEngine' => 'IbexaLegacySearchEngine',
    'EzSystemsPlatformInstaller' => 'IbexaRepositoryInstaller',
    'SilversolutionsEshop' => 'IbexaCommerceEshop',
    'SilversolutionsTools' => 'IbexaCommerceShopTools',
    'SilversolutionsTranslation' => 'IbexaCommerceTranslation',
    'SisoTools' => 'IbexaCommerceTools',
    'SisoPayment' => 'IbexaCommercePayment',
    'SisoPrice' => 'IbexaCommercePrice',
    'SisoSearch' => 'IbexaCommerceSearch',
    'SisoSpecificationsType' => 'IbexaCommerceSpecificationsType',
    'SisoBasket' => 'IbexaCommerceBasket',
    'SisoComparison' => 'IbexaCommerceComparison',
    'SisoEzStudio' => 'IbexaCommerceEzStudio',
    'SisoLocalOrderManagement' => 'IbexaCommerceLocalOrderManagement',
    'SisoNewsletter' => 'IbexaCommerceNewsletter',
    'SisoOgonePayment' => 'IbexaCommerceOgonePayment',
    'OneSky' => 'IbexaCommerceOneSky',
    'SisoPaypalPayment' => 'IbexaCommercePaypalPayment',
    'SisoQuickOrder' => 'IbexaCommerceQuickOrder',
    'SisoShopFrontend' => 'IbexaCommerceShopFrontend',
    'SisoTelecashPayment' => 'IbexaCommerceTelecashPayment',
    'SisoTestTools' => 'IbexaCommerceTestTools',
    'SisoVoucher' => 'IbexaCommerceVoucher',
    'EzPlatformAutomatedTranslation' => 'IbexaAutomatedTranslation',
    'eZBehat' => 'IbexaBehat',
];
